name: Deploy to Coolify
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: 'curl "${{ secrets.COOLIFY_ENDPOINT }}/api/v1/deploy?uuid=${{ secrets.COOLIFY_APP_UUID }}&force=false" --header "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"'